#+TITLE: From Sound to Story
#+SUBTITLE: Exploratory Data Analysis and Data Preparation of Morse Code Signals in R
#+AUTHOR: Matthew Younger - Pledged
#+DATE: \today

# Org Mode Settings:

#+OPTIONS: toc:2 num:t title:t author:t date:t
#+EXPORT_FILE_NAME: proposal.pdf
#+PROPERTY: header-args:python :results output :exports code
#+startup: indent overview hideblocks entitiespretty

#+BIBLIOGRAPHY: ./refs.bib
#+CITE_EXPORT: biblatex

# General LaTex Settings:

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER_OPTIONS: \usepackage[hidelinks]{hyperref}

# Latex Bibliography Settings (AMA)

#+LATEX_HEADER: \usepackage[style=apa,sorting=none,backend=biber]{biblatex}

* Summary
The purpose of this project (actually a sub-project) is to satisfy the requirements for a College-level
Data Science project, as well as to further my study of Machine Learning and Computer Science.

* Introduction and Background
The issue prompting this project is that while encoding and decoding CW/Morse is a relatively trivial task for /humans,/
it is not so for a computer. Morse is an intricate sequence of a short and long tones, differentiated by and grouped by
very precisely-timed intervals of relative silence. As such, each transmission shares common characteristics:

  1. Every observation has a tone of a specific frequency (Hz), accompanied by some amount of parasitic noise
     (whether the noise floor/"background noise", or man-made interference.

  2. A static pair of tonal emissions of a known length:
     - A dit is one measure of time <-- The standard measure \mu
     - A da is 3\mu measures of time.

  3. Strict voids between morse "characters", morse groups "letters", and groups of groups "words"
     - intra-character spacing of \mu
     - Inter-character spacing of 3\mu
     - Word/Character group spacing of 7\mu

* Methodology and Approach
** Visualization and EDA
The proposed approach is to use computer-generated training originally intended for a /Morse Learning Machine challenge/ from Kaggle [cite:@ag1le2014],
which will be analyzed in R using various candidate libraries to conduct *Exploratory Data Analysis* using:
  - Sonic Screwdriver [cite:@ssdriverCran]
  - Seewave [cite:@seewaveCran]
  - R Programming Language [cite:@RLang]
  - GNU Emacs [cite:@emacs]
  - GNU Org Mode [cite:@orgmode]

Proposed Visualization Techniques:
  1. Waveform with amplitude envelope and annotated tone on/off segments.
  2. Timeline of gaps per element, char, and word.
  3. Fourier transform and Mel spectrograms with artificial tone track overlay.
     #+begin_comment
     Conceptually, this should be similar to a waterfall display on a SDR radio,
     which could be helpful for visualizing which tones are what we're after and which are noise, etc.
     - [[https://en.wikipedia.org/wiki/Short-time_Fourier_transform][Wikipedia]]
     #+end_comment
  4. WPM estimate computed and annotated per the PARIS standard.
  5. Noise/SNR estimate for each recording.
     This information would be very valuable, as a high noise floor means any algorithm or
     conventional means of decoding the signal will presumably fail under sufficiently unfavorable conditions.
  6. Geometric Mean
     The simplest and most straighforward method is to measure dits and dashes through establishing a cut-off
     threshold for the tones via the geometric mean, as other studies have proven works reliably under ideal conditions, i.e. low noise and repeatable keying,
     [cite:@geomMeanK4ICY]. to continually evaluate what must be a dit/dash based on how the small bit of sound compares to this running calculation.
     This has been implemented on very minimal hardware such as an ardiuno, and it's admirable for its simplicity. I think this would be a good point to
     start the project, because it directly ties in with *evaluating and telling the story of the data,* which is a key deliverable for an
     Intro to Data Science course. From there, time permitting, perhaps the more advanced methods
     can be added to improve accuracy as needed.

Finally, an abundance of proven artificial data is readily available by way of previous work done on the AudioCW project, [cite:@audioCW].

** Machine Learning
This research could extend into Machine Learning and interact with other software in the project.
Conceptually, there are several machine learning techniques that could be applied:

    - *Naive Bayes Classification:*
      The author of the Kaggle dataset previously attempted to use Bayesian probability to estimate the /probability/ that
      a given tone is a dit/da or even an entire word fits inside a given /dictionary/ of words, [cite:@a1gleblog]. This could potentially
      be used by itself, or as a type of post-processing after a simpler and lighter algorithm does the bulk of the
      heavy lifting. Many practical conversations are very formulaic and predictable, due to the nature of HAM radio;
      The typical conversation usually consists of a callsign, a brief exchange of location, reception clarity, contest details,
      type of equipment being used to transmit and receive with, and an end of transmission "goodbye." The small sample space makes
      this a good option - even more so in the case of a robot that's exchanging a highly formulaic message sequence.

    - *Clustering:*
      There's promising literature that indicates clustering is very good for identifying bird sounds in audio recordings,
      particularly when combined with uniform manifold approximation and dimension reduction, [cite:@RSoundAnalysis].
      Just as birds have a distinct sound, so does each letter in CW. Per the guidance of the largest CW enthusiasts club in the country,
      humans learn best by recognizing entire sounds, as opposed to decoding the sequence of dashes and dits on the fly.

      Literature from the Long Island CW enthusiasts club, one of the largest clubs dedicated to morse code in the United States,
      emphasizes the effectiveness of having students identify entire acoustic sounds, rather than /counting/ the sequenes, [cite:@LICWTrainingMaterials].
      The group derives this understanding from careful review of Psychologist Ludwig Koch's study of learning Morse in 1936, having
      reached this conclusion after having an external entity translate Koch's work from the original German [cite:@KochReport].

* Timeline
Per the course outline, this project is to be managed under the *scrum project management* framework,
where we are encouraged as aspiring Data Scientists to continually /evaluate/ and /learn through our experiences/
with attention to our personal *skill stack and problem-solving abilities* as they relate to the task at hand.

Particularly, the project will be divided into four checkpoints:

1. *This proposal stage:* where the idea is pitched to a client or end-user.
2. *Literature Review*: wherein we evaluate other scholarly material to gain helpful insights.
   A core skill in good Science is having an adequate grasp of what others have tried before.
3. *Abstract:* Likewise, it is important that one's research is clearly articulated. An abstract helps
   other readers to efficiently determine whether our work is relevant to their studies.
4. *Presentation:* Finally, the conclusion of our study is presented to other scientists, students, colleagues,
   or more universally an end-user. Almost always done in a live "show-and-tell" style, this an opportunity to showcase
   a project and generate further interest to continue development or gain patronage for a future project (or to pass a class, in this case).

* Project Scope, Goals, and Constraints
** Scope and Goals
The primary focus of the project, at least for the duration of the course, will be primarily on EDA and data visualization. As /stretch goals,/
It would be beneficial to the project as a whole to continue exploring Machine Learning and using the data obtained from analyzing the data for
training the model.

** Constraints
There are several important constraints to the project. Foremost is that most modern work being done with Morse is in the hobby sphere.
It seems much less is being done in the field concerning morse, since it's considered an obsolete form of communication in the digital era.
As such, finding relevant literature to support the literature review phase of the project could prove difficult.

Additionally, the researcher is not acquainted with this type of analysis in R. This could lead to lost time spent troubleshooting issues unique to audio processing.
However, the larger field of Digital Signal Processing and Telecommunications may have higher-quality materials readily available.

* Evaluation
To aid in the visual evaluation, openly-available audio software, such as Tenacity [cite:@tenacityFOSS], can be used to compare our generated
visuals to that of a commonly-used audio tool. Synthetically-generated data can be interpreted visually in this way when it's pure tones without any noise or distortion,
which so too should this data if it's adequately cleaned and coherently represented.

Strictly in terms of measuring the success of any meaningful data extracted, the candidate Kaggle dataset mentions that
the /Levenshtein distance/ is the metric by which any candidate solution to their challenge is objectively evaluated. They provide this
as a part of the dataset, so the outcome is measurable beyond grading, should the project reach the Machine Learning stage.

Evaluation will be conducted formally by the course instructor per the University's grading policy,
the course syllabus, and the grading rubric as provided for each stage. In addition, less informal but no less
important evaluation is conducted by the researcher, per the aforementioned agile framework.

* Conclusion
Foremost, it is this project's intention to examine CW/Morse Code audio emissions gathered by microphone via digital signal processing
from a Data Science perspective. Audio files themselves are data structures which contain meaningful data, as well as outlier data: static, or literal noise, which can be
*cleaned, manipulated, analyzed, and visualized* in order to *extract meaningful insights and information:* an encoded message.

Ultimately, Data Science in this context will aid the parent program's ability to decode raw data from a microphone into actionable information that can either be displayed to an end-user
and/or executed directly by another program in an application stack as part of a larger project. As such, if this project can meet its goals , it not only adequately demonstrates
Data Science's intrinsic value in analyzing and understanding complicated information such as audio waveforms, but additionally showcases its value as an applied science to further other
other fields, such as Robotics, Telecommunications, and Machine Learning, which are likewise key areas relating to the larger project.

* References
#+print_bibliography:
